### ISSUE TITLE
There's problem in model.js source in method "generate"

### ISSUE THREAD

**Issue by yousefabdel1727** [zemlyansky/gpt-tfjs#6]
I'm try and fail to use it. i am use tfjs-backend-cpu because it is the fastest in android 👍. however i can train and can't generate. errors when try generate because something is wrong in blackSize

CONSOLE :
Training took 2027.4000000059605ms

GatherV2: the index value 11 is not in [0, 10]
at assert$1 (http://localhost:7700/test/tf.js:19365:12)
at _loop (http://localhost:7700/test/tf.js:106393:6)
at Object.gatherV2$1 [as kernelFunc] ([http://localhost:7700/test/tf.js:106398:6](http://localhost:7700/test/tf.js#106398:6))
at kernelFunc ([http://localhost:7700/test/tf.js:23856:25](http://localhost:7700/test/tf.js#23856:25))
at [http://localhost:7700/test/tf.js:23926:22](http://localhost:7700/test/tf.js#23926:22)
at Engine.scopedRun ([http://localhost:7700/test/tf.js:23693:20](http://localhost:7700/test/tf.js#23693:20))
at Engine.runKernelFunc ([http://localhost:7700/test/tf.js:23918:13](http://localhost:7700/test/tf.js#23918:13))
at Engine.runKernel ([http://localhost:7700/test/tf.js:23774:20](http://localhost:7700/test/tf.js#23774:20))
at gather_ ([http://localhost:7700/test/tf.js:33619:18](http://localhost:7700/test/tf.js#33619:18))
at gather__op ([http://localhost:7700/test/tf.js:24920:24](http://localhost:7700/test/tf.js#24920:24))

value 11 is blockSize because when change it. value change either.

always 11 is not in [0, 10] and if blockSize = 5 for example error 5 is not in [0, 4] 😔 in every time

this problem in source "generate" function in model.js

So Sorry for my bad English. because I'm still studying 🤗 it

**Comment by yousefabdel1727** [comment]
I'm using browser

**Comment by yousefabdel1727** [comment]
I'm discovered what is the problem. it's when use Wrong vocabSize and blockSize. Sorry my bad 😅👍

**Comment by martinjaggi** [comment]
just in case it helps, we also have a complete case of how to use `gpt-tfjs` in https://github.com/epfml/disco/
